language: scala
jdk:
  - openjdk8
scala:
   - 2.12.11
   - 2.13.2
script:
   - sbt ++$TRAVIS_SCALA_VERSION test
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
